In [3]:
import numpy as np

In [5]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [7]:
type(arr1)

numpy.ndarray

In [11]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
type(arr2)

numpy.ndarray

In [17]:
arr3=np.ones([3,6])
arr3

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
arr4=np.zeros([2,3])
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
print(arr2.ndim)

2


In [25]:
print(arr3.ndim)

2


In [29]:
# accessing array elements
arr1=np.array([1,2,3,4,5])
print(arr1[0])

1


In [31]:
arr1[4]

5

In [37]:
arr3[2]

array([1., 1., 1., 1., 1., 1.])

In [45]:
arr5=np.array([[1,2,3],[4,5,6]])
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
#2nd element on 1st row
arr5[1,2]

6